/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pav15p' at '16/04/16 10:54' with Gradle 2.12
 *
 * @author pav15p, @date 16/04/16 10:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
